networks:
  rede-local:

volumes:
  jenkins_volume:

services:
  jenkins:
    image: jenkins/jenkins:latest-jdk17
    user: root
    privileged: true
    networks:
      - rede-local
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins_container
    volumes:
      - jenkins_volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - $PWD/jenkins/vampi-analyzer.jenkinsfile:/var/jenkins_home/vampi-analyzer.jenkinsfile